package com.nationwide;

import java.util.Collections;

public class App {

    public static void main(String[] args) throws InterruptedException {

        long startTime = System.nanoTime();

        ProblemOne problemOne = new ProblemOne();
        ProblemTwo problemTwo = new ProblemTwo();
        ProblemThree problemThree = new ProblemThree();
        ProblemFour problemFour = new ProblemFour();
        ProblemFive problemFive = new ProblemFive();
        ProblemSix problemSix = new ProblemSix();
        ProblemSeven problemSeven = new ProblemSeven();
        ProblemEight problemEight = new ProblemEight();
        ProblemNine problemNine = new ProblemNine();
        ProblemTen problemTen = new ProblemTen();
        ProblemEleven problemEleven = new ProblemEleven();
        ProblemTwelve problemTwelve = new ProblemTwelve();
        ProblemThirteen problemThirteen = new ProblemThirteen();
        ProblemFourteen problemFourteen = new ProblemFourteen();
        ProblemFifteen problemFifteen = new ProblemFifteen();
        ProblemSixteen problemSixteen = new ProblemSixteen();
        ProblemSeventeen problemSeventeen = new ProblemSeventeen();
        ProblemEighteen problemEighteen = new ProblemEighteen();
        ProblemNineteen problemNineteen = new ProblemNineteen();
        ProblemTwenty problemTwenty = new ProblemTwenty();
        ProblemTwentyOne problemTwentyOne = new ProblemTwentyOne();
        ProblemTwentyTwo problemTwentyTwo = new ProblemTwentyTwo();
        ProblemTwentyThree problemTwentyThree = new ProblemTwentyThree();
        ProblemTwentyFive problemTwentyFive = new ProblemTwentyFive();
        ProblemTwentySix problemTwentySix = new ProblemTwentySix();
        ProblemTwentySeven problemTwentySeven = new ProblemTwentySeven();
        ProblemTwentyEight problemTwentyEight = new ProblemTwentyEight();
        ProblemTwentyNine problemTwentyNine = new ProblemTwentyNine();
        ProblemThirty problemThirty = new ProblemThirty();
        ProblemThirtyOne problemThirtyOne = new ProblemThirtyOne();
        ProblemThirtyTwo problemThirtyTwo = new ProblemThirtyTwo();
        ProblemThirtyThree problemThirtyThree = new ProblemThirtyThree();
        ProblemThirtyFour problemThirtyFour = new ProblemThirtyFour();
        ProblemThirtyFive problemThirtyFive = new ProblemThirtyFive();
        ProblemThirtySix problemThirtySix = new ProblemThirtySix();
        ProblemThirtySeven problemThirtySeven = new ProblemThirtySeven();
        ProblemThirtyEight problemThirtyEight = new ProblemThirtyEight();
        ProblemThirtyNine problemThirtyNine = new ProblemThirtyNine();
        ProblemForty problemForty = new ProblemForty();

        Thread thread = new Thread(problemOne);
        Thread thread1 = new Thread(problemTwo);
        Thread thread2 = new Thread(problemThree);
        Thread thread3 = new Thread(problemFour);
        Thread thread4 = new Thread(problemFive);
        Thread thread5 = new Thread(problemSix);
        Thread thread6 = new Thread(problemSeven);
        Thread thread7 = new Thread(problemEight);
        Thread thread8 = new Thread(problemNine);
        Thread thread9 = new Thread(problemTen);
        Thread thread10 = new Thread(problemEleven);
        Thread thread11 = new Thread(problemTwelve);
        Thread thread12 = new Thread(problemThirteen);
        Thread thread13 = new Thread(problemFourteen);
        Thread thread14 = new Thread(problemFifteen);
        Thread thread15 = new Thread(problemSixteen);
        Thread thread16 = new Thread(problemSeventeen);
        Thread thread17 = new Thread(problemEighteen);
        Thread thread18 = new Thread(problemNineteen);
        Thread thread19 = new Thread(problemTwenty);
        Thread thread20 = new Thread(problemTwentyOne);
        Thread thread21 = new Thread(problemTwentyTwo);
        Thread thread22 = new Thread(problemTwentyThree);
        Thread thread24 = new Thread(problemTwentyFive);
        Thread thread25 = new Thread(problemTwentySix);
        Thread thread26 = new Thread(problemTwentySeven);
        Thread thread27 = new Thread(problemTwentyEight);
        Thread thread28 = new Thread(problemTwentyNine);
        Thread thread29 = new Thread(problemThirty);
        Thread thread30 = new Thread(problemThirtyOne);
        Thread thread31 = new Thread(problemThirtyTwo);
        Thread thread32 = new Thread(problemThirtyThree);
        Thread thread33 = new Thread(problemThirtyFour);
        Thread thread34 = new Thread(problemThirtyFive);
        Thread thread35 = new Thread(problemThirtySix);
        Thread thread36 = new Thread(problemThirtySeven);
        Thread thread37 = new Thread(problemThirtyEight);
        Thread thread38 = new Thread(problemThirtyNine);
        Thread thread39 = new Thread(problemForty);

        thread.start();
        thread1.start();
        thread2.start();
        thread3.start();
        thread4.start();
        thread5.start();
        thread6.start();
        thread7.start();
        thread8.start();
        thread9.start();
        thread10.start();
        thread11.start();
        thread12.start();
        thread13.start();
        thread14.start();
        thread15.start();
        thread16.start();
        thread17.start();
        thread18.start();
        thread19.start();
        thread20.start();
        thread21.start();
        thread22.start();
        thread24.start();
        thread25.start();
        thread26.start();
        thread27.start();
        thread28.start();
        thread29.start();
        thread30.start();
        thread31.start();
        thread32.start();
        thread33.start();
        thread34.start();
        thread35.start();
        thread36.start();
        thread37.start();
        thread38.start();
        thread39.start();


        thread.join();
        System.out.println("Problem 1: " + problemOne.getValue());
        thread1.join();
        System.out.println("Problem 2: " + problemTwo.getValue());
        thread2.join();
        System.out.println("Problem 3: " + problemThree.getValue());
        thread3.join();
        System.out.println("Problem 4: " + problemFour.getValue());
        thread4.join();
        System.out.println("Problem 5: " + problemFive.getValue());
        thread5.join();
        System.out.println("Problem 6: " + problemSix.getValue());
        thread6.join();
        System.out.println("Problem 7: " + problemSeven.getValue());
        thread7.join();
        System.out.println("Problem 8: " + problemEight.getValue());
        thread8.join();
        System.out.println("Problem 9: " + problemNine.getValue());
        thread9.join();
        System.out.println("Problem 10: " + problemTen.getValue());
        thread10.join();
        System.out.println("Problem 11: " + problemEleven.getValue());
        thread11.join();
        System.out.println("Problem 12: " + problemTwelve.getValue());
        thread12.join();
        System.out.println("Problem 13: " + problemThirteen.getValue());
        thread13.join();
        System.out.println("Problem 14: " + problemFourteen.getValue());
        thread14.join();
        System.out.println("Problem 15: " + problemFifteen.getValue());
        thread15.join();
        System.out.println("Problem 16: " + problemSixteen.getValue());
        thread16.join();
        System.out.println("Problem 17: " + problemSeventeen.getValue());
        thread17.join();
        System.out.println("Problem 18: " + problemEighteen.getValue());
        thread18.join();
        System.out.println("Problem 19: " + problemNineteen.getValue());
        thread19.join();
        System.out.println("Problem 20: " + problemTwenty.getValue());
        thread20.join();
        System.out.println("Problem 21: " + problemTwentyOne.getValue());
        thread21.join();
        System.out.println("Problem 22: " + problemTwentyTwo.getValue());
        thread22.join();
        System.out.println("Problem 23: " + problemTwentyThree.getValue());
        thread24.join();
        System.out.println("Problem 25: " + problemTwentyFive.getValue());
        thread25.join();
        System.out.println("Problem 26: " + problemTwentySix.getValue());
        thread26.join();
        System.out.println("Problem 27: " + problemTwentySeven.getValue());
        thread27.join();
        System.out.println("Problem 28: " + problemTwentyEight.getValue());
        thread28.join();
        System.out.println("Problem 29: " + problemTwentyNine.getValue());
        thread29.join();
        System.out.println("Problem 30: " + problemThirty.getValue());
        thread30.join();
        System.out.println("Problem 31: " + problemThirtyOne.getValue());
        thread31.join();
        System.out.println("Problem 32: " + problemThirtyTwo.getValue());
        thread32.join();
        System.out.println("Problem 33: " + problemThirtyThree.getValue());
        thread33.join();
        System.out.println("Problem 34: " + problemThirtyFour.getValue());
        thread34.join();
        System.out.println("Problem 35: " + problemThirtyFive.getValue());
        thread35.join();
        System.out.println("Problem 36: " + problemThirtySix.getValue());
        thread36.join();
        System.out.println("Problem 37: " + problemThirtySeven.getValue());
        thread37.join();
        System.out.println("Problem 38: " + problemThirtyEight.getValue());
        thread38.join();
        System.out.println("Problem 39: " + problemThirtyNine.getValue());
        thread39.join();
        System.out.println("Problem 40: " + problemForty.getValue());

        long endTime = System.nanoTime();
        double totalTime = (double) (endTime - startTime) / 1000000000;
        System.out.println("Time to run is: " + totalTime + " seconds");
    }
}
